/** Entity evidence, shareholding diagram and linked KYC share one registry source. */
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { requireGlobalDocumentAccess } from '@/lib/document-access'
import { prisma } from '@/lib/prisma'
import { addEntityOwnership, linkKycToEntity, saveEntityFiling, saveEntityProfile } from '@/actions/entity-records'
import { EntityActionForm } from '@/components/legal/entity-action-form'
import { EntityField, fieldClass, SourceReference } from '@/components/legal/entity-fields'
import { EntityProfileFields } from '@/components/legal/entity-profile-fields'
import { FILING_TYPES } from '@/lib/entity-input'

export default async function EntityDetail({ params }: { params: Promise<{ id: string }> }) {
  await requireGlobalDocumentAccess()
  const { id } = await params
  const [profile, profiles, unlinkedKyc] = await Promise.all([
    prisma.entityProfile.findUnique({ where: { id }, include: { filings: { orderBy: { due_date: 'asc' } }, owned_by: { include: { owner_entity: true } }, kyc_documents: true } }),
    prisma.entityProfile.findMany({ where: { id: { not: id } }, orderBy: { legal_name: 'asc' } }),
    prisma.kycDocument.findMany({ where: { entity_profile_id: null }, select: { id: true, document_name: true, entity: true }, orderBy: { document_name: 'asc' } }),
  ])
  if (!profile) notFound()
  return <div className="space-y-8">
    <Link href="/legal/compliance/entities" className="text-sm text-primary underline">All entities</Link>
    <header><h1 className="text-2xl font-semibold">{profile.legal_name}</h1><p className="mt-2 text-sm text-muted-foreground">{profile.jurisdiction} · Registration {profile.registration_number ?? 'not supplied'}</p></header>
    <div className="grid gap-6 border-y border-border py-5 sm:grid-cols-2"><div><h2 className="mb-2 text-xs text-muted-foreground">Registered agent</h2><p>{profile.registered_agent_name ?? 'Not supplied'}</p><p className="text-sm text-muted-foreground">{profile.registered_agent_contact}</p></div><div><h2 className="mb-2 text-xs text-muted-foreground">Registered office</h2><p>{profile.registered_office ?? 'Not supplied'}</p></div></div>
    <section className="space-y-4"><h2 className="text-lg font-medium">Ownership</h2>
      {profile.owned_by.length ? <>
        <div aria-label="Ownership relationships" className="grid gap-3 border border-border p-5"><div className="flex flex-wrap justify-center gap-4">{profile.owned_by.map((holding) => <div key={holding.id} className="text-center"><div className="border border-border px-4 py-2 text-sm">{holding.owner_entity?.legal_name ?? holding.owner_name}</div><div className="py-3 text-xs text-muted-foreground">{holding.percentage?.toFixed() ?? 'Unknown'}{holding.percentage === null ? ' stake' : '%'} ↓</div></div>)}</div><div className="mx-auto border border-primary px-4 py-2 text-sm">{profile.legal_name}</div></div>
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="py-2">Shareholder</th><th>Stake</th><th>Effective date</th><th>Evidence</th></tr></thead><tbody>{profile.owned_by.map((holding) => <tr key={holding.id} className="border-b border-border"><td className="py-3">{holding.owner_entity?.legal_name ?? holding.owner_name}</td><td className="font-mono">{holding.percentage?.toFixed() ?? 'Unknown'}{holding.percentage !== null && '%'}</td><td>{holding.effective_date?.toISOString().slice(0, 10) ?? 'Unknown'}</td><td><SourceReference value={holding.source_reference} /></td></tr>)}</tbody></table></div>
      </> : <p className="text-sm text-muted-foreground">No sourced shareholding records. Ownership is unknown.</p>}
      <details><summary className="cursor-pointer text-sm">Add shareholding</summary><EntityActionForm action={addEntityOwnership} className="mt-4"><input name="owned_entity_id" value={id} type="hidden" /><div className="grid gap-4 sm:grid-cols-2"><EntityField label="Owner entity"><select className={fieldClass} name="owner_entity_id"><option value="">External shareholder or unselected</option>{profiles.map((item) => <option key={item.id} value={item.id}>{item.legal_name}</option>)}</select></EntityField><EntityField label="Or external shareholder name"><input name="owner_name" className={fieldClass} /></EntityField><EntityField label="Stake percentage, leave blank if unknown"><input name="percentage" inputMode="decimal" className={fieldClass} /></EntityField><EntityField label="Effective date"><input name="effective_date" type="date" className={fieldClass} /></EntityField><EntityField label="Source reference *"><input name="source_reference" required className={fieldClass} /></EntityField></div></EntityActionForm></details>
    </section>
    <section className="space-y-4 border-t border-border pt-6"><h2 className="text-lg font-medium">Registration, annual reports and appointments</h2>
      {!profile.filings.length && <p className="text-sm text-muted-foreground">No filing evidence recorded.</p>}
      {profile.filings.map((filing) => <details key={filing.id} className="border-b border-border py-3"><summary className="cursor-pointer text-sm">{filing.filing_type.replaceAll('_', ' ')} · {filing.reporting_period ?? 'Period not supplied'} · {filing.filed_date ? `Filed ${filing.filed_date.toISOString().slice(0, 10)}` : filing.due_date ? `Due ${filing.due_date.toISOString().slice(0, 10)}` : 'Date unknown'}</summary><EntityActionForm action={saveEntityFiling} className="mt-4" reset={false}><input name="id" type="hidden" value={filing.id} /><input name="entity_profile_id" type="hidden" value={id} /><input name="filing_type" type="hidden" value={filing.filing_type} /><div className="grid gap-3 sm:grid-cols-2"><EntityField label="Reporting period"><input name="reporting_period" className={fieldClass} defaultValue={filing.reporting_period ?? ''} /></EntityField><EntityField label="Due date"><input name="due_date" type="date" className={fieldClass} defaultValue={filing.due_date?.toISOString().slice(0, 10) ?? ''} /></EntityField><EntityField label="Filed date"><input name="filed_date" type="date" className={fieldClass} defaultValue={filing.filed_date?.toISOString().slice(0, 10) ?? ''} /></EntityField><EntityField label="Receipt / source reference"><input name="source_reference" className={fieldClass} defaultValue={filing.source_reference ?? ''} /></EntityField><EntityField label="Notes"><input name="notes" className={fieldClass} defaultValue={filing.notes ?? ''} /></EntityField></div></EntityActionForm></details>)}
      <details><summary className="cursor-pointer text-sm">Add filing or appointment</summary><EntityActionForm action={saveEntityFiling} className="mt-4"><input name="entity_profile_id" value={id} type="hidden" /><div className="grid gap-4 sm:grid-cols-2"><EntityField label="Record type"><select name="filing_type" className={fieldClass}>{FILING_TYPES.map((item) => <option key={item}>{item}</option>)}</select></EntityField><EntityField label="Reporting period"><input name="reporting_period" className={fieldClass} /></EntityField><EntityField label="Due date"><input name="due_date" type="date" className={fieldClass} /></EntityField><EntityField label="Filed date"><input name="filed_date" type="date" className={fieldClass} /></EntityField><EntityField label="Receipt / source reference"><input name="source_reference" className={fieldClass} /></EntityField><EntityField label="Notes"><input name="notes" className={fieldClass} /></EntityField></div></EntityActionForm></details>
    </section>
    <section className="space-y-4 border-t border-border pt-6"><div className="flex justify-between"><h2 className="text-lg font-medium">KYC</h2><Link className="text-sm text-primary underline" href={`/legal/compliance/entities/kyc?profile=${id}`}>Open KYC register</Link></div>{profile.kyc_documents.map((doc) => <div key={doc.id} className="flex justify-between border-b border-border py-3 text-sm"><span>{doc.document_name}</span><span>{doc.status.replaceAll('_', ' ')}</span></div>)}{!profile.kyc_documents.length && <p className="text-sm text-muted-foreground">No KYC records explicitly linked.</p>}
      {!!unlinkedKyc.length && <EntityActionForm action={linkKycToEntity} submitLabel="Link existing KYC"><input name="entity_profile_id" value={id} type="hidden" /><EntityField label="Existing unlinked record"><select name="kyc_document_id" required className={fieldClass}>{unlinkedKyc.map((doc) => <option key={doc.id} value={doc.id}>{doc.entity}: {doc.document_name}</option>)}</select></EntityField></EntityActionForm>}
    </section>
    <details className="border-t border-border pt-5"><summary className="cursor-pointer text-sm">Edit entity profile</summary><EntityActionForm action={saveEntityProfile} className="mt-5" reset={false}><EntityProfileFields profile={profile} /></EntityActionForm></details>
  </div>
}
