/** Entity-led overview with actual review, access and signing exceptions beside Slack operations. */
import Link from "next/link"
import { prisma } from "@/lib/prisma"
import { requireSession } from "@/lib/auth"
import { documentScope, isGlobalDocumentUser } from "@/lib/document-access"
import { loadUsdRates } from "@/lib/fx-rates"
import { currencyCode, formatMoney, usdTotal } from "@/lib/money"

export default async function CommandCenterPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireSession()
  if (!await isGlobalDocumentUser(session)) return <div className="space-y-5"><h1 className="text-2xl font-semibold">Legal workspace</h1><p className="text-muted-foreground">Open your authorized documents or request access from the legal team.</p><div className="flex gap-6 text-primary"><Link href="/legal/documents">Your documents</Link><Link href="/legal/access">Request document access</Link><Link href="/legal/backups">Your exports</Link></div></div>
  const query = await searchParams
  const currency = currencyCode(query.currency)
  const scope = await documentScope(session)
  const now = new Date()
  const [entities, reviews, requests, signatures, amounts, rates, exports, artifactCounts] = await Promise.all([
    prisma.entityProfile.findMany({ orderBy: { legal_name: "asc" }, include: { _count: { select: { filings: true, kyc_documents: true, owned_by: true } } } }),
    prisma.reviewTask.findMany({ where: { status: "OPEN", schedule: { active: true }, due_date: { lte: now } }, include: { schedule: { select: { title: true } } }, orderBy: { due_date: "asc" }, take: 8 }),
    prisma.documentAccessRequest.count({ where: { status: "PENDING" } }),
    prisma.legalDocument.findMany({ where: { AND: [scope, { lifecycle_status: "AWAITING_SIGNATURE" }] }, select: { id: true, title: true }, take: 5, orderBy: { updated_at: "asc" } }),
    prisma.legalDocument.findMany({ where: { AND: [scope, ...(currency ? [{ currency }] : [])] }, select: { value: true, currency: true } }),
    loadUsdRates(),
    prisma.documentExport.findMany({ where: { requested_by: session.userId }, orderBy: { created_at: "desc" }, take: 1 }),
    prisma.documentArtifact.groupBy({ by: ["stage"], _count: true }),
  ])
  const total = usdTotal(amounts, rates)
  const latestExport = exports[0]
  return <div className="space-y-7">
    <div className="flex flex-wrap justify-between items-center gap-4"><h1 className="text-3xl font-semibold tracking-tight">Entities & legal operations</h1><div className="flex gap-5 text-sm text-primary"><Link href="/legal/repositories">Repositories</Link><Link href="/legal/backups">Download all</Link></div></div>
    <div className="grid gap-4 border-y border-border py-5 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Agreement value, USD reporting</p><p className="text-xl font-mono tabular-nums">{total.included ? formatMoney(total.total, "USD") : "Unknown"}</p><p className="text-xs text-muted-foreground">{total.missing} missing amount or current FX</p></div><div><p className="text-xs text-muted-foreground">Legal entities recorded</p><p className="text-xl font-mono tabular-nums">{entities.length}</p><p className="text-xs text-muted-foreground">Arena codes remain separate</p></div><div><p className="text-xs text-muted-foreground">Latest document export</p><p className="text-xl">{latestExport?.status ?? "Not requested"}</p><p className="text-xs text-muted-foreground">{latestExport?.verified_at ? `Manually verified ${latestExport.verified_at.toISOString().slice(0, 10)}` : "Manual verification not recorded"}</p></div></div>
    <form className="flex flex-wrap items-center gap-3 text-sm"><label htmlFor="dashboard-currency">Agreement currency filter</label><input id="dashboard-currency" name="currency" defaultValue={currency ?? ""} pattern="[A-Z]{3}" placeholder="All currencies" className="border border-input bg-background rounded px-3 py-2"/><button className="border border-border rounded px-3 py-2">Apply</button><Link className="text-primary" href="/legal/currencies">FX sources</Link></form>
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_330px]">
      <div className="space-y-8"><section><div className="flex justify-between items-center gap-3 border-b border-border pb-3"><h2 className="text-lg font-medium">Legal entities</h2><Link href="/legal/compliance/entities" className="text-primary text-sm">Manage entities</Link></div>{entities.map((entity) => <Link key={entity.id} href={`/legal/compliance/entities/${entity.id}`} className="block border-b border-border py-4"><div className="flex justify-between gap-4"><h3 className="font-medium">{entity.legal_name}</h3><span className="text-sm text-muted-foreground">{entity.jurisdiction}</span></div><p className="mt-2 text-sm text-muted-foreground">Registration: {entity.registration_number ?? "Not supplied"}. {entity._count.filings} filings, {entity._count.kyc_documents} KYC records, {entity._count.owned_by} ownership records.</p></Link>)}{!entities.length && <p className="py-8 text-sm text-muted-foreground">No sourced entity profiles recorded. Add registration and ownership evidence to build the entity workspace.</p>}</section>
      <section><div className="flex justify-between items-center border-b border-border pb-3"><h2 className="text-lg font-medium">Reviews requiring action</h2><Link href="/legal/compliance/reviews" className="text-primary text-sm">All review schedules</Link></div>{reviews.map((review) => <div key={review.id} className="flex justify-between gap-4 border-b border-border py-3 text-sm"><span>{review.schedule.title}</span><span className="font-mono tabular-nums">Due {review.due_date.toISOString().slice(0, 10)}</span></div>)}{!reviews.length && <p className="py-5 text-sm text-muted-foreground">No open due reviews in recorded schedules. Unconfigured documents have no inferred schedule.</p>}</section>
      <section><h2 className="text-lg font-medium">Document repositories</h2><div className="grid grid-cols-1 sm:grid-cols-3 mt-3 border-y border-border">{[["template", "Templates"], ["populated", "Populated"], ["signed", "Signed"]].map(([stage, name]) => <Link key={stage} href={`/legal/repositories?stage=${stage}`} className="py-4 pr-5"><div className="text-primary">{name}</div><div className="text-xl font-mono tabular-nums">{artifactCounts.find((row) => row.stage === stage)?._count ?? 0}</div></Link>)}</div><p className="text-xs text-muted-foreground mt-2">Verified artifact records. Historical documents remain in the agreement register.</p></section></div>
      <aside className="space-y-7 xl:border-l xl:border-border xl:pl-7"><section><h2 className="text-lg font-medium">Work from Slack</h2><p className="mt-3 text-sm text-muted-foreground">Use the connected legal app to find records and act on assigned work. Permissions follow your individual account.</p><div className="mt-4 space-y-3 font-mono text-xs"><p>/legal status</p><p>/legal signatures</p><p>/legal find [counterparty]</p></div><Link href="/legal/ops-monitor" className="mt-4 block text-sm text-primary">Integration evidence and failures</Link></section><section><h2 className="text-lg font-medium">Legal decisions</h2><Link href="/legal/access" className="block border-b border-border py-4 text-sm">{requests} access requests pending review</Link>{signatures.map((doc) => <Link href={`/legal/documents/${doc.id}`} key={doc.id} className="block border-b border-border py-4 text-sm"><span className="text-muted-foreground">Awaiting signature</span><p className="mt-1">{doc.title}</p></Link>)}<Link href="/legal/generate" className="block border-b border-border py-4 text-sm text-primary">Contract generation and worker status</Link></section><div className="flex flex-wrap gap-4 text-sm text-primary"><Link href="/legal/litigation">Litigation</Link><Link href="/legal/arbitration">Arbitration</Link><Link href="/legal/policies">Policies & Procedures</Link></div></aside>
    </div>
  </div>
}
