services:
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    restart: unless-stopped
    volumes:
      - opensign-files:/usr/src/app/files
    depends_on:
      - mongo
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST_URL}/api/app
      - PUBLIC_URL=${HOST_URL}
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo-container
    restart: unless-stopped
    volumes:
      - data-volume:/data/db
    networks:
      - app-network

  client:
    image: opensign/opensign:main
    container_name: OpenSign-container
    restart: unless-stopped
    depends_on:
      - server
    env_file: .env.prod
    environment:
      - PUBLIC_URL=${HOST_URL}
    networks:
      - app-network

  caddy:
    image: caddy:2
    container_name: caddy-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - HOST=${HOST}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  caddy_data:
  caddy_config:
  opensign-files:
