/** Review work queue, auditable completion evidence and sourced dependencies. */
import Link from 'next/link'
import { requireGlobalDocumentAccess } from '@/lib/document-access'
import { prisma } from '@/lib/prisma'
import { addCalendarMonths, utcDay } from '@/lib/review-rules'
import { createReviewSchedule, finishReview, importReviewDependencies, recordReviewChange, refreshReviewTasks, setReviewScheduleActive } from '@/actions/review-schedules'
import { EntityActionForm } from '@/components/legal/entity-action-form'
import { EntityField, fieldClass, SourceReference } from '@/components/legal/entity-fields'

export default async function ReviewSchedulesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireGlobalDocumentAccess()
  const query = await searchParams
  const status = query.status === 'COMPLETED' ? 'COMPLETED' : 'OPEN'
  const [schedules, tasks, taskCount, documents, policies, users, dependencies] = await Promise.all([
    prisma.reviewSchedule.findMany({ orderBy: { title: 'asc' } }),
    prisma.reviewTask.findMany({ where: { status, ...(status === 'OPEN' ? { schedule: { active: true } } : {}) }, include: { schedule: true }, orderBy: { due_date: 'asc' }, take: 200 }),
    prisma.reviewTask.count({ where: { status, ...(status === 'OPEN' ? { schedule: { active: true } } : {}) } }),
    prisma.legalDocument.findMany({ select: { id: true, title: true }, orderBy: { title: 'asc' } }),
    prisma.policyDocument.findMany({ select: { id: true, title: true }, orderBy: { title: 'asc' } }),
    prisma.appUser.findMany({ where: { is_active: true }, select: { id: true, full_name: true }, orderBy: { full_name: 'asc' } }),
    prisma.reviewDependency.findMany({ include: { source: true, target: true }, orderBy: { created_at: 'desc' } }),
  ])
  const names = new Map(users.map((user) => [user.id, user.full_name]))
  const now = utcDay(new Date())
  return <div className="space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><h1 className="text-2xl font-semibold">Review schedules</h1><Link href="/legal/policies" className="text-sm text-primary underline">Policies & Procedures</Link></header>
    <nav className="flex gap-6 border-b border-border pb-3 text-sm"><Link href="/legal/compliance/reviews" className={status === 'OPEN' ? 'text-primary' : 'text-muted-foreground'}>Open reviews</Link><Link href="?status=COMPLETED" className={status === 'COMPLETED' ? 'text-primary' : 'text-muted-foreground'}>Completion history</Link></nav>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Showing {tasks.length} of {taskCount} {status.toLowerCase()} reviews. Due dates stay separate from completion.</p><EntityActionForm action={refreshReviewTasks} submitLabel="Refresh scheduled tasks"><span className="sr-only">Materialize current review occurrences</span></EntityActionForm></div>
    {!tasks.length && <p className="text-sm text-muted-foreground">No review tasks in this view. Add a sourced schedule or refresh its occurrences.</p>}
    <div className="divide-y divide-border">{tasks.map((task) => <article key={task.id} className="py-5"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-sm font-medium">{task.schedule.title}</h2><p className="mt-1 text-xs text-muted-foreground">{task.schedule.kind === 'PUBLIC' ? 'Public document' : 'Internal policy'} · {names.get(task.schedule.owner_id ?? '') ?? 'Owner unavailable'} · {task.trigger_kind.toLowerCase()}</p></div><p className="text-sm">{task.status === 'OPEN' && task.due_date < now ? 'Overdue · ' : 'Due '}{task.due_date.toISOString().slice(0, 10)}</p></div>{task.trigger_reference && <p className="mt-2 whitespace-pre-line text-xs text-muted-foreground">{task.trigger_reference}</p>}{task.status === 'COMPLETED' ? <div className="mt-3 text-sm"><p>Completed {task.completed_at?.toISOString().slice(0, 10)} by {names.get(task.completed_by ?? '') ?? 'Recorded user'}</p><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{task.evidence}</p></div> : <details className="mt-3"><summary className="cursor-pointer text-xs text-primary">Record review completion</summary><EntityActionForm action={finishReview} submitLabel="Complete review" className="mt-3"><input name="task_id" value={task.id} type="hidden" /><EntityField label="Review findings / evidence *"><textarea className={fieldClass} name="evidence" required maxLength={4000} rows={2} /></EntityField></EntityActionForm></details>}</article>)}</div>
    <section className="space-y-4 border-t border-border pt-6"><h2 className="text-lg font-medium">Schedules</h2>{schedules.map((schedule) => <div key={schedule.id} className="border-b border-border py-3"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-sm">{schedule.title}</h3><p className="text-xs text-muted-foreground">{schedule.kind === 'PUBLIC' ? 'Every 14 days for six calendar months' : `Every ${schedule.interval_months} months`} · Starts {schedule.start_date.toISOString().slice(0, 10)} · {schedule.active ? 'Active' : 'Paused'}</p><code className="text-xs text-muted-foreground">{schedule.id}</code>{schedule.kind === 'PUBLIC' && !schedule.steady_interval_months && addCalendarMonths(schedule.start_date, 6) <= now && <p className="mt-1 text-xs text-destructive">Initial review period ended. Steady-state cadence needs confirmation.</p>}</div><EntityActionForm action={setReviewScheduleActive} submitLabel={schedule.active ? 'Pause schedule' : 'Resume schedule'}><input name="schedule_id" type="hidden" value={schedule.id} /><input name="active" type="hidden" value={String(!schedule.active)} /></EntityActionForm></div></div>)}
      <details><summary className="cursor-pointer text-sm">Add review schedule</summary><EntityActionForm action={createReviewSchedule} className="mt-4"><div className="grid gap-4 sm:grid-cols-2"><EntityField label="Schedule title *"><input className={fieldClass} name="title" required /></EntityField><EntityField label="Kind"><select className={fieldClass} name="kind"><option value="PUBLIC">Public-facing document</option><option value="INTERNAL">Internal Policies & Procedures</option></select></EntityField><EntityField label="Public document"><select className={fieldClass} name="document_id"><option value="">Choose only for public reviews</option>{documents.map((doc) => <option key={doc.id} value={doc.id}>{doc.title}</option>)}</select></EntityField><EntityField label="Internal policy"><select className={fieldClass} name="policy_id"><option value="">Choose only for internal reviews</option>{policies.map((policy) => <option key={policy.id} value={policy.id}>{policy.title}</option>)}</select></EntityField><EntityField label="Owner *"><select className={fieldClass} name="owner_id" required><option value="">Select owner</option>{users.map((user) => <option key={user.id} value={user.id}>{user.full_name}</option>)}</select></EntityField><EntityField label="Confirmed review start *"><input className={fieldClass} name="start_date" type="date" required /></EntityField><EntityField label="Internal interval"><select className={fieldClass} name="interval_months"><option value="">Choose for internal policy</option>{[4,5,6].map((month) => <option key={month} value={month}>{month} months</option>)}</select></EntityField><EntityField label="Public interval after six months, only if confirmed"><input className={fieldClass} type="number" min="1" max="24" name="steady_interval_months" placeholder="Leave blank when unknown" /></EntityField><EntityField label="Evidence for start and cadence *"><input className={fieldClass} name="source_reference" required /></EntityField></div></EntityActionForm></details>
    </section>
    <section className="space-y-4 border-t border-border pt-6"><h2 className="text-lg font-medium">Dependency triggers</h2><p className="text-sm text-muted-foreground">Import Arvind&apos;s sourced correlation table. No dependencies are assumed.</p>{dependencies.map((edge) => <div key={edge.id} className="grid gap-1 border-b border-border py-3 text-sm"><p>{edge.source.title} → {edge.target.title}</p><SourceReference value={edge.source_reference} /></div>)}<details><summary className="cursor-pointer text-sm">Import correlation rows</summary><EntityActionForm action={importReviewDependencies} submitLabel="Validate and import" className="mt-4"><div className="grid gap-4"><EntityField label="Source table reference *"><input className={fieldClass} name="source_reference" required /></EntityField><EntityField label='JSON rows using schedule IDs: [{"source_schedule_id":"...","target_schedule_id":"..."}]'><textarea className={`${fieldClass} font-mono`} name="rows" required rows={5} /></EntityField></div></EntityActionForm></details><details><summary className="cursor-pointer text-sm">Record a source change</summary><EntityActionForm action={recordReviewChange} submitLabel="Trigger affected reviews" className="mt-4"><div className="grid gap-4 sm:grid-cols-2"><EntityField label="Changed source"><select className={fieldClass} name="schedule_id" required><option value="">Select schedule</option>{schedules.map((schedule) => <option key={schedule.id} value={schedule.id}>{schedule.title}</option>)}</select></EntityField><EntityField label="Stable change reference / version ID *"><input className={fieldClass} name="change_reference" required /></EntityField></div></EntityActionForm></details></section>
  </div>
}
